### ISSUE TITLE
Accordion, No animation for the first time

### ISSUE THREAD

**Issue by Cacivy** [yuche/vue-strap#223]
repeat

1. http://yuche.github.io/vue-strap/#accordion

2.close only one at a time.

3.click Panel #2 or Panel #3 or Panel #4  **no animation**

4. click again  **width animation**

**Comment by TheShiftExchange** [comment]
@Cacivy - why did you close this? I noticed the same issue? Did you fix it?

**Comment by Cacivy** [comment]
you must set max-height 
```css
/* panel.vue */
.collapse-transition {
  transition: max-height .5s ease;
  overflow: hidden;
  max-height: 111px; /*or 999px*/
}
```
