### ISSUE TITLE
width of datepicker does not support "100%"

### ISSUE THREAD

**Issue by PeakTai** [yuche/vue-strap#83]
```html
<datepicker :value.sync="entry_date" format="yyyy-MM-dd" width="100%"></datepicker>
```
It does not work!

Otherwise，will datepicker support format with time?

**Comment by amanpatel** [comment]
Yes. "width" is not a valid property on the datepicker component. You can probably achieve what you are trying to do by styling the input that is generated by the component.


```css
div.datepicker {display:block;}
div.datepicker > input.form-control {
    width:100% !important;
}
```
